spring:
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false

#logging
logging:
  level:
    org:
      springframework:
        data: debug

app:
  token: 'c6ca2e46-34d1-11e8-b467-0ed5f89f718b'
